# Generated by Django 4.1.5 on 2023-05-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_options_alter_audience_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fio',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='num_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер недели'),
        ),
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together={('teacher', 'time_class', 'date')},
        ),
    ]
